#!/usr/bin/env bash
# R-Quest training configuration.
export BASE_MODEL=${RQUEST_BASE_MODEL:-Qwen/Qwen3-4B-Base}
export VALIDITY_MODEL_PATH=$BASE_MODEL
export VALIDITY_DATASET=${RQUEST_VALIDITY_DATASET:-jinyuan222/rzero-validity-rl-terra-v1-clean-v1}
export VALIDITY_EXPERIMENT_NAME=qwen3_4b_validity_rl_terra_clean_v1
export VALIDITY_MAX_STEPS=15
export VALIDITY_ROLLOUT_BATCH_SIZE=512
export VALIDITY_ROLLOUT_N=8
export VALIDITY_GPU_IDS=${RQUEST_GPU_IDS:-0,1,2,3}
export VALIDITY_RZERO_ENABLED=1
export VALIDITY_RZERO_DIVERSITY_MODE=semantic_novelty_gate
export VALIDITY_RZERO_NOVELTY_K=8
export VALIDITY_RZERO_NOVELTY_SEED=43
export VALIDITY_RZERO_SEMANTIC_MODEL=$BASE_MODEL
export VALIDITY_RZERO_SEMANTIC_LOCAL_FILES_ONLY=1
export VALIDITY_RZERO_SEMANTIC_GPU_IDS=${RQUEST_GPU_IDS:-0,1,2,3}
export VALIDITY_RZERO_SEMANTIC_GPU_MEMORY_UTILIZATION=0.80
export VALIDITY_RZERO_SEMANTIC_WORKER_BATCH_SIZE=8192
export TERRA_REPLAY_DATASET=$VALIDITY_DATASET
export TERRA_REPLAY_CONFIG=default
export TERRA_REPLAY_RATIO=0.1
export TERRA_REPLAY_SEED=1
export QUESTION_GPU_IDS=${RQUEST_GPU_IDS:-0,1,2,3}
IFS=',' read -r -a RQUEST_GPUS <<< "$QUESTION_GPU_IDS"
if [ "${#RQUEST_GPUS[@]}" -ne 4 ]; then
    echo 'The paper configuration requires four GPUs (RQUEST_GPU_IDS=0,1,2,3).' >&2
    return 2 2>/dev/null || exit 2
fi
export QUESTIONER_TRAIN_GPU_IDS=${RQUEST_GPUS[0]},${RQUEST_GPUS[1]}
export VLLM_GPU_IDS=${RQUEST_GPUS[2]},${RQUEST_GPUS[3]}
export QUESTIONER_MAX_STEPS=5 QUESTIONER_MERGE_STEP=5
export SOLVER_MAX_STEPS=15 SOLVER_MERGE_STEP=15
export QUESTIONER_ROLLOUT_BATCH_SIZE=512 QUESTIONER_ROLLOUT_N=4
export QUESTIONER_GLOBAL_BATCH_SIZE=4
export QUESTIONER_MAX_RESPONSE_LENGTH=4096
export SOLVER_MAX_RESPONSE_LENGTH=4096 SOLVER_ROLLOUT_BATCH_SIZE=512
export SOLVER_GENERATE_SAMPLES=2500
export SOLVER_UPLOAD_MIN_SCORE=0.3 SOLVER_UPLOAD_MAX_SCORE=0.8
export MODEL_ABBR=${RQUEST_RUN_NAME:-rquest_qwen3_4b_k8}
export RZERO_NUM_ROUNDS=${RQUEST_ROUNDS:-5}
export VALIDITY_RZERO_INITIAL_SOLVER=${RQUEST_INITIAL_SOLVER:-${VALIDITY_SAVE_PATH:-${STORAGE_PATH}/models/qwen3_4b_validity_rl_terra_clean_v1}/global_step_15/actor/huggingface}
